name: Continuous Integration + Deployment

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

env:
  DOTNET_NOLOGO: "true"
  CONFIGURATION: Release
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"
  DOTNET_SYSTEM_GLOBALIZATION_PREDEFINED_CULTURES_ONLY: "false"

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifacts-location: ${{ steps.build.outputs.artifacts-location }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_SHARED_ROLE }}
          aws-region: us-east-1

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install CDK
        run: npm install --global cdk

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1

      - name: Display .NET Info
        run: dotnet --info

      - name: Build
        id: build
        run: |
          dotnet run \
            --verbosity minimal \
            --project cicd/Cicd.BuildDriver/Cicd.BuildDriver.csproj -- \
            --version ${{ github.run_number }}

      - name: Test
        run: |
          dotnet test \
            --logger trx \
            --no-build

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    concurrency: dev
    environment: Development
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE }}
          aws-region: us-east-1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1

      - name: Display .NET Info
        run: dotnet --info

      - name: Deploy to Dev
        run: |
          dotnet run \
            --project cicd/Cicd.DeployDriver/Cicd.DeployDriver.csproj -- \
            --artifacts-location ${{ needs.build.outputs.artifacts-location }} \
            --environment dev

  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    needs:
      - build
      - deploy-dev
    concurrency: prod
    environment: Production
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_PROD_ROLE }}
          aws-region: us-east-1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1

      - name: Display .NET Info
        run: dotnet --info

      - name: Deploy to Prod
        run: |
          dotnet run \
            --project cicd/Cicd.DeployDriver/Cicd.DeployDriver.csproj -- \
            --artifacts-location ${{ needs.build.outputs.artifacts-location }} \
            --environment prod
